application: gcpsm
module: default
version: 1
runtime: go
api_version: go1.9
instance_class: F1
automatic_scaling:
  min_idle_instances: 0
  max_idle_instances: automatic  # default value
  min_pending_latency: 30ms  # default value
  max_pending_latency: automatic
  max_concurrent_requests: 80

handlers:
- url: /api/admin/.*
  login: admin
  script: _go_app
- url: /swagger-ui
  static_dir: swagger-ui
  login: admin
- url: /.*
  script: _go_app